### ISSUE TITLE
Fix links outputted for `.github/ISSUE_TEMPLATE/config.yml`

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/governance#52]
File content should be:
```
blank_issues_enabled: false
contact_links:
  - name: PureScript Discourse
    url: https://discourse.purescript.org/
    about: Ask and answer questions on the PureScript discussion forum.
  - name: PureScript Discord
    url: https://purescript.org/chat
    about: Ask and answer questions on the PureScript chat.
```
